Update borg backup scripts

diff --git a/roles/systemd/files/scripts/backup-remote b/roles/systemd/files/scripts/backup-remote
--- a/roles/systemd/files/scripts/backup-remote
+++ b/roles/systemd/files/scripts/backup-remote
@@ -32,44 +32,60 @@ fi
 export BORG_PASSPHRASE
 export BORG_REPO=ssh://"${SSH_USER}@${SSH_HOST}:${SSH_PORT}"/mnt/user/backup/borg_andrei
 export BORG_REMOTE_PATH='/usr/bin/borg'
+# Check paths
+declare -a backup_paths=()
+declare -a check_paths=(
+    "/tank/backup/pgsql"
+    "/tank/backup/gitea"
+    "${CONTAINER_DATA}/nextcloud/data"
+    "${CONTAINER_DATA}/bitwarden/data"
+    "${BACKUP_USER_HOME}/src"
+)
+for p in "${check_paths[@]}"; do
+    if [[ -d "$p" ]]; then
+        backup_paths+=("$p")
+    else
+        echo "WARN: cannot backup $p: not found"
+    fi
+done
+if [[ ${#backup_paths[@]} -eq 0 ]]; then
+    echo "No backup paths found"
+    exit 1
+fi
+echo "Backing up ${backup_paths[*]}"
 
-# some helpers and error handling:
-info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
-trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM
+# error handling
+trap 'echo Backup interrupted >&2; exit 2' INT TERM
 
-info "Starting backup"
+echo "Starting backup"
 
 # Backup the most important directories into an archive named after
 # the machine this script is currently running on:
 
-borg create                           \
-    --stats                           \
-    --show-rc                         \
-    --compression auto,zstd           \
-    --exclude-caches                  \
-    ::'{hostname}-{now}'              \
-    /tank/backup/pgsql                \
-    /tank/backup/gitea                \
-    "$CONTAINER_DATA"/nextcloud/data  \
-    "$CONTAINER_DATA"/bitwarden/data  \
-    "${BACKUP_USER_HOME}"/src         \
+borg create                 \
+    --stats                 \
+    --show-rc               \
+    --compression auto,zstd \
+    --exclude-caches        \
+    ::'{hostname}-{now}'    \
+    "${backup_paths[*]}"
 
 backup_exit=$?
 
-info "Pruning repository"
+echo "Pruning repository"
 
 # Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
 # archives of THIS machine. The '{hostname}-' prefix is very important to
 # limit prune's operation to this machine's archives and not apply to
 # other machines' archives also:
 
-borg prune                          \
-    --list                          \
-    --prefix '{hostname}-'          \
-    --show-rc                       \
-    --keep-daily    2               \
-    --keep-weekly   2               \
-    --keep-monthly  6               \
+borg prune                 \
+    --list                 \
+    --prefix '{hostname}-' \
+    --show-rc              \
+    --keep-daily    2      \
+    --keep-weekly   2      \
+    --keep-monthly  6
 
 prune_exit=$?
 
@@ -77,11 +93,11 @@ prune_exit=$?
 global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))
 
 if [ ${global_exit} -eq 0 ]; then
-    info "Backup and Prune finished successfully"
+    echo "Backup and Prune finished successfully"
 elif [ ${global_exit} -eq 1 ]; then
-    info "Backup and/or Prune finished with warnings"
+    echo "Backup and/or Prune finished with warnings"
 else
-    info "Backup and/or Prune finished with errors"
+    echo "Backup and/or Prune finished with errors"
 fi
 
 unset BORG_PASSPHRASE BORG_REPO
diff --git a/roles/systemd/files/scripts/backup-root b/roles/systemd/files/scripts/backup-root
--- a/roles/systemd/files/scripts/backup-root
+++ b/roles/systemd/files/scripts/backup-root
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 BORG_REPO=${BORG_REPO:-/tank/backup/borg}
 # Setting this, so the repo does not need to be given on the commandline:
@@ -7,47 +7,64 @@ export BORG_REPO
 # Setting this, so you won't be asked for your repository passphrase:
 # export BORG_PASSPHRASE=''
 
-# some helpers and error handling:
-info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
-trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM
+# Check paths
+declare -a backup_paths=()
+declare -a check_paths=(
+    "/etc"
+    "/srv"
+    "/home"
+    "/root"
+    "/var/www"
+)
+for p in "${check_paths[@]}"; do
+    if [[ -d "$p" ]]; then
+        backup_paths+=("$p")
+    else
+        echo "WARN: cannot backup $p: not found"
+    fi
+done
+if [[ ${#backup_paths[@]} -eq 0 ]]; then
+    echo "No backup paths found"
+    exit 1
+fi
+echo "Backing up ${backup_paths[*]}"
 
-info "Starting backup"
+# error handling
+trap 'echo Backup interrupted >&2; exit 2' INT TERM
+
+echo "Starting backup"
 
 # Backup the most important directories into an archive named after
 # the machine this script is currently running on:
 
-borg create                         \
-    --stats                         \
-    --show-rc                       \
-    --compression auto,zstd         \
-    --exclude-caches                \
-    --exclude '/home/*/.cache/*'    \
-    --exclude '*.qcow2'             \
-    --exclude '/srv/nfs'            \
-    --exclude '/*/.snapshots'       \
-    ::'{hostname}-{now}'            \
-    /etc                            \
-    /srv                            \
-    /home                           \
-    /root                           \
-    /var/www                        \
+borg create                      \
+    --stats                      \
+    --show-rc                    \
+    --compression auto,zstd      \
+    --exclude-caches             \
+    --exclude '/home/*/.cache/*' \
+    --exclude '*.qcow2'          \
+    --exclude '/srv/nfs'         \
+    --exclude '/*/.snapshots'    \
+    ::'{hostname}-{now}'         \
+    "${backup_paths[*]}"
 
 backup_exit=$?
 
-info "Pruning repository"
+echo "Pruning repository"
 
 # Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
 # archives of THIS machine. The '{hostname}-' prefix is very important to
 # limit prune's operation to this machine's archives and not apply to
 # other machines' archives also:
 
-borg prune                          \
-    --list                          \
-    --prefix '{hostname}-'          \
-    --show-rc                       \
-    --keep-daily    2               \
-    --keep-weekly   2               \
-    --keep-monthly  6               \
+borg prune                 \
+    --list                 \
+    --prefix '{hostname}-' \
+    --show-rc              \
+    --keep-daily    2      \
+    --keep-weekly   2      \
+    --keep-monthly  6
 
 prune_exit=$?
 
@@ -55,11 +72,11 @@ prune_exit=$?
 global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))
 
 if [ ${global_exit} -eq 0 ]; then
-    info "Backup and Prune finished successfully"
+    echo "Backup and Prune finished successfully"
 elif [ ${global_exit} -eq 1 ]; then
-    info "Backup and/or Prune finished with warnings"
+    echo "Backup and/or Prune finished with warnings"
 else
-    info "Backup and/or Prune finished with errors"
+    echo "Backup and/or Prune finished with errors"
 fi
 
 unset BORG_REPO
